server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/NicolasSalinasR/tingeso_backend_2
          search-paths: config-data
  application:
    name: config-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true # Registro habilitado
    fetch-registry: true       # Permite al cliente obtener la lista de instancias registradas
  instance:
    prefer-ip-address: true # Utiliza la dirección IP en lugar del hostname
